# ===================================================================
# CONFIGURAÇÃO DO CONEXÃO COM O NEON POSTGRESQL
# ===================================================================
spring.datasource.url=jdbc:postgresql://ep-shy-hall-b495wrf2-pooler.c-6.us-east-2.aws.neon.tech/meuDb?sslmode=require
spring.datasource.username=meuDb_owner
spring.datasource.password=npg_7nMiJFhR0wZE
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# ===================================================================
# Cria e atualiza as tabelas automaticamente no Neon
spring.jpa.hibernate.ddl-auto=update

# Exibe o SQL no console para acompanhamento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto específico para o PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
